### ISSUE TITLE
Remove start up message "[KillTrack] AddOn Loaded!"

### ISSUE THREAD

**Issue by Bonkeybee** [SharpWoW/KillTrack#18]
Please add an option or remove the addon startup message from chat: "[KillTrack] AddOn Loaded!"

**Comment by tflo** [comment]
I second this.

This is a widespread issue, not only with this add-on. 

These “loaded” messages are not a problem if people are running just a couple of add-ons. But once you run more add-ons, the chat window gets completely cluttered with these messages, with the result that messages that really have to say something (e.g. profession cooldown reminders, Garrison cache warnings, etc.) get visually lost.

I already have manually patched about a dozen different add-ons to get rid of this. But this is tedious of course, since you have to reapply the patch with every release.

If you decide to add a “loaded” message, then please also add a config option to suppress it.

**Comment by Sharparam** [comment]
There will now be a config option to enable the load message (disabled by default, can be toggled with `/kt loadmessage` or `/kt lm`). Reducing the spam in the chat on load is indeed a good thing.

I'll push out a new version with this change (as well as updated TOC version numbers).

**Comment by tflo** [comment]
Thank you very much, really appreciated!
