### ISSUE TITLE
Command that shows last Server Time you killed a rare

### ISSUE THREAD

**Issue by nazzler** [SharpWoW/KillTrack#19]
For someone who is farming rares it would be super helpful to see, when looking up at the kill count, also the last time the rare was killed, so to calculate respawn time and be on spawn spot at the correct time.

**Comment by Sharparam** [comment]
Should be a rather small thing to add I think. I'll see if I can get around to adding it, I need to go through some addons and bump their version support anyway.

**Comment by Sharparam** [comment]
v2.31.0 has been released now which includes tracking of the last time each mob was killed. You can see this by hovering over the mob in the GUI list (`/kt list`), or as an additional output when looking up a mob via slash commands (`/kt target` or `/kt lookup`).

Mobs that haven't been killed since the update will not have this data yet and as such the tooltip in the list won't show for them, and there won't be additional time output for them in slash commands. On the next kill of the mob the data will be updated.

The format of the time output can also be configured in the interface options for KillTrack, following the standard Lua `date` format (you can read more about that here: https://www.lua.org/pil/22.1.html), the default is the ISO format, e.g. `2022-05-08 13:21`.

Closing issue as implemented, if there are any issues with the feature feel free to re-open :)
